site_name: Mario Torres
site_url: https://mariotorrestech.github.io/
repo_url: https://github.com/mariotorrestech/mariotorrestech.github.io
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - About Me: about.md
  - Certfications:
    - CISSP Overview: certifications/cissp.md
    - Domain 1 - Asset Security: certifications/domains/domain1.md
    - Domain 2 - Asset Security: certifications/domains/domain2.md
    - Domain 3 - Security Engineering: certifications/domains/domain3.md
    - Domain 4 - Communication and Network Security: certifications/domains/domain4.md
    - Domain 5 - Identity and Access Management: certifications/domains/domain5.md
    - Domain 6 - Security Assessment and Testing: certifications/domains/domain6.md
    - Domain 7 - Security Operations: certifications/domains/domain7.md
    - Domain 8 - Software Development Security: certifications/domains/domain8.md
    
  - Homelab:
      - Homelab Overview: homelab/index.md
      - Pi-hole DNS: homelab/pihole.md
      - Step-ca PKI: homelab/step-ca.md
      - Nginx Proxy Manager: homelab/npm.md
      - AD Lab: homelab/activedirectory.md
      - Web App Lab: homelab/webapplab.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/m
  favicon: assets/favicon.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features: 
    - navigation.footer
    - navigation.top
    - toc.follow
    - toc.integrate

  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.blocks.caption

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/tmario/
